# Generated by Django 6.1.1 on 2026-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
