# Generated by Django 6.1.1 on 2026-09-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0005_alter_product_subcategory_alter_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='start',
            new_name='stars',
        ),
    ]
